---
title: "Group 2_Lab 1"
author: "Zimu Lyu"
date: "10/9/2020"
output: html_document
---

# bronx1

```{r}
library(xlsx) 
bronx1<-read.xlsx("/Users/cleardog/BA/MGMT 6962 Data Analytics/Lab Data/nyhousing/rollingsales_bronx.xls", pattern = "BOROUGH", stringsAsFactors = FALSE, sheetIndex = 1, startRow = 5, header = TRUE)
View(bronx1)

bronx1$SALE.PRICE<-sub("\\$","",bronx1$SALE.PRICE) 
bronx1$SALE.PRICE<-as.numeric(gsub(",","", bronx1$SALE.PRICE)) 
bronx1$GROSS.SQUARE.FEET<-as.numeric(gsub(",","", bronx1$GROSS.SQUARE.FEET)) 
bronx1$LAND.SQUARE.FEET<-as.numeric(gsub(",","", bronx1$LAND.SQUARE.FEET)) 
bronx1$SALE.DATE<- as.Date(gsub("[^]:digit:]]","",bronx1$SALE.DATE)) 
bronx1$YEAR.BUILT<- as.numeric(gsub("[^]:digit:]]","",bronx1$YEAR.BUILT)) 
bronx1$ZIP.CODE<- as.character(gsub("[^]:digit:]]","",bronx1$ZIP.CODE)) 

help("gsub")
```

```{r}
# Model 1
m1_data <- bronx1[which(bronx1$GROSS.SQUARE.FEET > 0),]

plot(log(m1_data$GROSS.SQUARE.FEET), log(m1_data$SALE.PRICE)) 
m1_data <- bronx1[which(bronx1$GROSS.SQUARE.FEET > 0),]
m1 <- lm(log(m1_data$SALE.PRICE) ~ log(m1_data$GROSS.SQUARE.FEET))
summary(m1)
abline(m1,col = "red",lwd = 2)
plot(resid(m1))
```


```{r}
# Model 2
m2_data <- bronx1[which(bronx1$GROSS.SQUARE.FEET > 0 & bronx1$LAND.SQUARE.FEET> 0),]

m2 <- lm(log(m2_data$SALE.PRICE) ~ log(m2_data$GROSS.SQUARE.FEET) + log(m2_data$LAND.SQUARE.FEET) + factor(m2_data$NEIGHBORHOOD))
summary(m2)
plot(resid(m2))

# Suppress intercept
m2a <- lm(log(m2_data$SALE.PRICE) ~ 0 + log(m2_data$GROSS.SQUARE.FEET) + log(m2_data$LAND.SQUARE.FEET) + factor(m2_data$NEIGHBORHOOD))
summary(m2a)
plot(resid(m2a))
```

```{r}
# Model 3
m3_data <- bronx1[which(bronx1$GROSS.SQUARE.FEET > 0 & bronx1$LAND.SQUARE.FEET> 0),]

m3 <- lm(log(m3_data$SALE.PRICE) ~ 0 + log(m3_data$GROSS.SQUARE.FEET) + log(m3_data$LAND.SQUARE.FEET) + factor(m3_data$NEIGHBORHOOD) + factor(m3_data$BUILDING.CLASS.CATEGORY))
summary(m3)
plot(resid(m3))
```

```{r}
# Model 4
m4_data <- bronx1[which(bronx1$GROSS.SQUARE.FEET > 0 & bronx1$LAND.SQUARE.FEET> 0),]

m4 <- lm(log(m4_data$SALE.PRICE) ~ 0 + log(m4_data$GROSS.SQUARE.FEET) + log(m4_data$LAND.SQUARE.FEET) + factor(m4_data$NEIGHBORHOOD) * factor(m4_data$BUILDING.CLASS.CATEGORY))
summary(m4)
plot(resid(m4)) # better than model 3
```

# bronx2

```{r}
minprice <- 10000
bronx1 <- bronx1[which(bronx1$SALE.PRICE >= minprice),]
nval <- dim(bronx1)[1]

bronx1$ADDRESSONLY <- gsub("[,][[:print:]]*","",gsub("[ ]+","",trim(bronx1$ADDRESS))) 
bronxadd <- unique(data.frame(bronx1$ADDRESSONLY, bronx1$ZIP.CODE,stringsAsFactors=FALSE)) 
names(bronxadd) <- c("ADDRESSONLY","ZIP.CODE") 
bronxadd <- bronxadd[order(bronxadd$ADDRESSONLY),] # sort by numbers in address
head(bronxadd)
duplicates <- duplicated(bronx1$ADDRESSONLY)
head(duplicates)

for(i in 1:2345) {
  if(duplicates[i] == FALSE) 
    dupadd <- bronxadd[bronxadd$duplicates,1]
}
head(dupadd) # This means there are no duplicate values in this column
```

```{r}
nsample <- 450
addsample <- bronxadd[sample.int(dim(bronxadd),size=nsample),] 

library(ggmap)
addrlist <- paste(addsample$ADDRESSONLY, "NY", addsample$ZIP.CODE, "US", sep=" ") 
querylist <- geocode(addrlist) ## I cannot install curl package.

matched <- (querylist$lat != 0 && querylist$lon !=0 ) 
addsample <- cbind(addsample,querylist$lat, querylist$lon) 
names(addsample) <- c("ADDRESSONLY","ZIPCODE","Latitude","Longitude") # correct the column na
adduse <- merge(bronx1,addsample)

adduse <- adduse[!is.na(adduse$Latitude),]
mapcoord <- adduse[,c(2,3,24,25)]

table(mapcoord$NEIGHBORHOOD)

mapcoord$NEIGHBORHOOD <- as.factor(mapcoord$NEIGHBORHOOD)
map <- get_map(location = 'Bronx', zoom = 12)#Zoom 11 or 12
ggmap(map) + geom_point(aes(x = mapcoord$Longitude, y = mapcoord$Latitude, size =1, color=mapcoord$NEIGHBORHOOD), data = mapcoord) +theme(legend.position = "none") 

mapmeans <- cbind(adduse,as.numeric(mapcoord$NEIGHBORHOOD))
colnames(mapmeans)[26] <- "NEIGHBORHOOD"

keeps <- c("ZIP.CODE","NEIGHBORHOOD","TOTAL.UNITS","LAND.SQUARE.FEET","GROSS.SQUARE.FEET","SALE.PRICE","Latitude","Longitude") 
mapmeans <- mapmeans[keeps] #Dropping others
mapmeans$NEIGHBORHOOD <- as.numeric(mapcoord$NEIGHBORHOOD) 

for(i in 1:8){
  mapmeans[,i]=as.numeric(mapmeans[,i]) 
} 

#Classification
mapcoord$class<as.numeric(mapcoord$NEIGHBORHOOD)
nclass <- dim(mapcoord)[1]
split <- 0.8
trainid <- sample.int(nclass,floor(split*nclass))
testid <- (1:nclass)[-trainid]

mappred <- mapcoord[testid,]
mappred$class <- as.numeric(mappred$NEIGHBORHOOD) 

kmax <- 10
knnpred <- matrix(NA,ncol=kmax,nrow=length(testid))
knntesterr <- rep(NA,times=kmax)
for (i in 1:kmax){		# loop over k
        knnpred[,i] <- knn(mapcoord[trainid,3:4],mapcoord[testid,3:4],cl=mapcoord[trainid,2],k=i)
        knntesterr[i] <- sum(knnpred[,i]!=mapcoord[testid,2])/length(testid)
} 
knntesterr

#Clustering
mapobj <- kmeans(mapmeans,5, iter.max=10, nstart=5, algorithm = c("Hartigan-Wong", "Lloyd", "Forgy", "MacQueen"))
fitted(mapobj,method=c("centers","classes"))
mapobj$centers

library(cluster)
clusplot(mapmeans, mapobj$cluster, color=TRUE, shade=TRUE, labels=2, lines=0) 

library(fpc)
plotcluster(mapmeans, mapobj$cluster)

mapmeans1 <- mapmeans[,-c(1,3,4)]
mapobjnew <- kmeans(mapmeans1,5, iter.max=10, nstart=5, algorithm = c("Hartigan-Wong", "Lloyd", "Forgy", "MacQueen"))
fitted(mapobjnew,method=c("centers","classes"))
clusplot(mapmeans1, mapobjnew$cluster, color=TRUE, shade=TRUE, labels=2, lines=0) 
plotcluster(mapmeans1, mapobjnew$cluster)
ggmap(map) + geom_point(aes(x = mapcoord$Longitude, y = mapcoord$Latitude, size =1, color=mapobjnew$cluster), data = mapcoord)
```

# ctree2

```{r}
pairs(~ Fertility + Education + Catholic, data = swiss, subset = Education < 20, main = "Swiss data, Education < 20")
# Find relationships between three variables.
require(party)
swiss_ctree <- ctree(Fertility ~ Agriculture + Education + Catholic, data = swiss)
plot(swiss_ctree)
```

# gpairs1

```{r}
y <- data.frame(A=c(rep("red", 100), rep("blue", 100)),
                B=c(rnorm(100),round(rnorm(100,5,1),1)), C=runif(200),
                D=c(rep("big", 150), rep("small", 50)),
                E=rnorm(200))
library(gpairs)
gpairs(y) # There is an error. Why?
```
```{r}
allexamples <- FALSE
data(iris)
gpairs(iris)

if (allexamples) {
  gpairs(iris, upper.pars = list(scatter = 'stats'),
         scatter.pars = list(pch = substr(as.character(iris$Species), 1, 1),
                             col = as.numeric(iris$Species)),
         stat.pars = list(verbose = FALSE))
  gpairs(iris, lower.pars = list(scatter = 'corrgram'),
         upper.pars = list(conditional = 'boxplot', scatter = 'loess'),
         scatter.pars = list(pch = 20))
}

```

# knn1

```{r}
data(Leaves)
head(Leaves)
gpairs(Leaves[1:10], lower.pars = list(scatter = 'loess'))
if (allexamples) {
  gpairs(Leaves[1:10], upper.pars = list(scatter = 'stats'),
         lower.pars = list(scatter = 'corrgram'),
         stat.pars = list(verbose = FALSE), gap = 0)
  corrgram(Leaves[,-33])
}

runexample <- FALSE
if (runexample) {
  data(NewHavenResidential)
  gpairs(NewHavenResidential)
}
```

```{r}
require(kknn)
m <- dim(iris)[1]
val <- sample(1:m, size = round(m/3), replace = FALSE, 
	prob = rep(1/m, m)) 
iris.learn <- iris[-val,]
iris.valid <- iris[val,]
iris.kknn <- kknn(Species~., iris.learn, iris.valid, distance = 1,
	kernel = "triangular")
summary(iris.kknn)
fit <- fitted(iris.kknn)
table(iris.valid$Species, fit)
pcol <- as.character(as.numeric(iris.valid$Species))
pairs(iris.valid[1:4], pch = pcol, col = c("green3", "red")[(iris.valid$Species != fit)+1])
help("pairs")
```

# knn2

```{r}
data(ionosphere)
head(ionosphere)
ionosphere.learn <- ionosphere[1:200,]
ionosphere.valid <- ionosphere[-c(1:200),]
fit.kknn <- kknn(class ~ ., ionosphere.learn, ionosphere.valid)
table(ionosphere.valid$class, fit.kknn$fit)
(fit.train1 <- train.kknn(class ~ ., ionosphere.learn, kmax = 15, 
	kernel = c("triangular", "rectangular", "epanechnikov", "optimal"), distance = 1))
table(predict(fit.train1, ionosphere.valid), ionosphere.valid$class)
```

```{r}
(fit.train2 <- train.kknn(class ~ ., ionosphere.learn, kmax = 15, 
	kernel = c("triangular", "rectangular", "epanechnikov", "optimal"), distance = 2)) # different distance
table(predict(fit.train2, ionosphere.valid), ionosphere.valid$class)
```

# kmeans1

```{r}
data(swiss)
sclass <- kmeans(swiss[2:6], 3) 
table(sclass$cluster, swiss[,1]) 
```

# mosaic

```{r}
data(HairEyeColor)
help("mosaicplot")
mosaicplot(HairEyeColor)
margin.table(HairEyeColor,3)
margin.table(HairEyeColor,c(1,3))
```

# nyt

```{r}
nyt1 <- read.csv("/Users/cleardog/BA/MGMT 6962 Data Analytics/Lab Data/dds_ch2_nyt/nyt1.csv")
nyt1 <- nyt1[which(nyt1$Impressions>0 & nyt1$Clicks>0 & nyt1$Age>0),]

nnyt1 <- dim(nyt1)[1] # rows
sampling.rate = 0.9
num.test.set.labels = nnyt1*(1.-sampling.rate)

# traning set
training <- sample(1:nnyt1,sampling.rate*nnyt1, replace = FALSE)
train <-  subset(nyt1[training,],select = c(Age,Impressions))

# test set
testing <- setdiff(1:nnyt1,training)
test <- subset(nyt1[testing,],select = c(Age,Impressions))

# dependent variable
cg <- nyt1$Gender[training]
true.labels <- nyt1$Gender[testing]

library(class)
classif <- knn(train,test,cg,k=5)
classif
attributes(.Last.value) 
``` 

