---
title: "Lab3"
output: html_document
---

# Use rpart to build the regression tree.

```{r}
library(rpart)
library(rpart.plot)
data("msleep")
str(msleep)
help("msleep")
```

```{r}
mSleepDF1 <- msleep[, c(3,6,10,11)]
str(mSleepDF1)
head(mSleepDF1)
```

```{r}
help("rpart")
help("rpart.plot")
```

```{r}
sleepModel_1 <- rpart(sleep_total ~ ., data = mSleepDF1, method = "anova") 
sleepModel_1
```

```{r}
rpart.plot(sleepModel_1, type = 2, digits = 3, fallen.leaves = TRUE)
rpart.plot(sleepModel_1, type = 3, digits = 3, fallen.leaves = TRUE)
rpart.plot(sleepModel_1, type = 3, digits = 4, fallen.leaves = TRUE)

```

# Use Ctree to build the classification ree.

```{r}
library(C50)
data("iris")
head(iris)
str(iris)
table(iris$Species)
```

```{r}
set.seed(9850)
grn <- runif(nrow(iris))
help("runif")
order(grn)
irisrand <- iris[order(grn),]
str(irisrand)
```

```{r}
classificationmodel1 <- C5.0(irisrand[1:100, -5], irisrand[1:100, 5])
classificationmodel1
```

```{r}
summary(classificationmodel1)
```

```{r}
prediction1 <- predict(classificationmodel1, irisrand[101:150,])
prediction1
```

```{r}
table(irisrand[101:150,5], prediction1)
```

```{r}
plot(classificationmodel1)
```

# Use NaiveBayes classifier.

```{r}
library("e1071")
classifier <- naiveBayes(iris[, 1:4], iris[, 5])
table(predict(classifier, iris[, -5]), iris[, 5], dnn = list('predicted', 'actual'))
```

```{r}
classifier$apriori
classifier$tables$Petal.Length
```

```{r}
plot(function(x) dnorm(x, 1.462, 0.1736640), 0, 8, col = "red", 
     main = "Petal length distribution for the 3 different species")
curve(dnorm(x, 4.260, 0.4699110), add = TRUE, col = "blue")
curve(dnorm(x, 5.552, 0.5518947), add = TRUE, col = "green")
```




