---
title: "Factor Analysis"
author: "Zimu Lyu"
output: html_document
---

# fa1

```{r}
v1 <- c(1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,4,5,6)
v2 <- c(1,2,1,1,1,1,2,1,2,1,3,4,3,3,3,4,6,5)
v3 <- c(3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,5,4,6)
v4 <- c(3,3,4,3,3,1,1,2,1,1,1,1,2,1,1,5,6,4)
v5 <- c(1,1,1,1,1,3,3,3,3,3,1,1,1,1,1,6,4,5)
v6 <- c(1,1,1,2,1,3,3,3,4,3,1,1,1,2,1,6,5,4)
m1 <- cbind(v1,v2,v3,v4,v5,v6)
cor(m1)
```

```{r}
factanal(m1, factors = 3) # default: rotation="varimax"
factanal(m1, factors = 3, rotation = "promax")

factanal(~v1+v2+v3+v4+v5+v6, factors = 3, scores = "Bartlett")$scores
```

```{r}
prcomp(m1)
```

# fa2

```{r}
library(Hmisc)
library(GPArotation)
AthleticsData <- spss.get("AthleticsData.sav") 
## Error in read.spss(file, use.value.labels = use.value.labels, to.data.frame = to.data.frame, : unable to open file: 'No such file or directory'
```

# fa4

```{r}
data(epi) 
## data set ‘epi’ not found
```

# fa5

```{r}
set.seed(1234)
N <- 200 # number of observations
P <- 6 # number of variables
Q <- 2 # number of factors

# 6x2 matrix
Lambda <- matrix(c(0.7,-0.4, 0.8,0, -0.2,0.9, -0.3,0.4, 0.3,0.7, -0.8,0.1),
                 nrow=P, ncol=Q, byrow=TRUE)
Lambda
```

```{r}
library(mvtnorm)
FF <- rmvnorm(N, mean=c(5, 15), sigma=diag(Q)) # factor scores
dim(FF)
E <- rmvnorm(N, rep(0, P), diag(P)) # matrix with normal errors, mean 0
dim(E)
X <- FF %*% t(Lambda) + E # matrix with variable values
dim(X)
Xdf <- data.frame(X)
head(Xdf)
```

```{r}
library(psych)
fa(X, nfactors=2, rotate="varimax")$loadings # factor analysis
```

```{r}
Xdi <- lapply(Xdf, function(x) cut(x, breaks=c(-Inf, median(x), Inf), ordered=TRUE)) # list: X1~X6
Xdidf <- do.call("data.frame", Xdi) # combine
Xdidf
XdiNum <- data.matrix(Xdidf)
head(XdiNum)
```

```{r}
library(polycor)
pc <- hetcor(Xdidf, ML=TRUE) # component correlations
pc
```

```{r}
faPC <- fa(r=pc$correlations, nfactors=2, n.obs=N, rotate="varimax")
faPC$loadings
```

```{r}
# same as above
faPCdirect <- fa.poly(XdiNum, nfactors=2, rotate="varimax")
faPCdirect$fa$loadings 
```

```{r}
# visualization
factor.plot(faPCdirect$fa, cut=0.5)
fa.diagram(faPCdirect)
```

```{r}
fa.parallel(XdiNum, cor='poly') # parallel analysis for dichotomous data
vss(pc$correlations, n.obs=N, rotate="varimax") # very simple structure
```

```{r}
library(random.polychor.pa)
random.polychor.pa(data.matrix=XdiNum, nrep=5, q.eigen=0.99)
```

# fa1

```{r}
data(iqitems) # data set ‘iqitems’ not found
data(ability) # data set ‘ability’ not found
```

