---
title: "Logistic regression, multiple models"
author: "Zimu Lyu"
output: html_document
---

# Logistic Regression 

```{r}
url <- "http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
heartdata <-read.csv(url,header = FALSE)
head(heartdata) 
colnames(heartdata) <- c("age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca", "thal","hd")
head(heartdata)
```

```{r}
str(heartdata) 
```

```{r}
heartdata[heartdata =="?"] <- NA
str(heartdata)
```

```{r}
# convert into factors
heartdata[heartdata$sex == 0,]$sex <- "F"  
heartdata[heartdata$sex == 1,]$sex <- "M"
heartdata$sex <- as.factor(heartdata$sex)

heartdata$cp <- as.factor(heartdata$cp)
heartdata$fbs <- as.factor(heartdata$fbs)
heartdata$restecg <-as.factor(heartdata$restecg)
heartdata$exang <- as.factor(heartdata$exang)
heartdata$slope <- as.factor(heartdata$slope)

heartdata$ca <- as.integer(heartdata$ca)
heartdata$ca <- as.factor(heartdata$ca)

heartdata$thal <-as.integer(heartdata$thal)
heartdata$thal <-as.factor(heartdata$thal)

heartdata$hd <- ifelse(test = heartdata$hd == 0, yes = "Healthy", no = "Unhealthy")
heartdata$hd <- as.factor(heartdata$hd)

str(heartdata)
```

```{r}
# check "NA"s, 6 rows
nrow(heartdata[is.na(heartdata$ca) | is.na(heartdata$thal),])
```

```{r}
heartdata[is.na(heartdata$ca) | is.na(heartdata$thal),]
```

```{r}
# remove 6 rows with NA
nrow(heartdata) 
heartdata <-heartdata[!(is.na(heartdata$ca) | is.na(heartdata$thal)),]
nrow(heartdata)
```

```{r}
xtabs(~heartdata$hd + heartdata$sex, data = heartdata)
xtabs(~ heartdata$hd + heartdata$cp, data = heartdata)
xtabs(~ heartdata$hd + heartdata$fbs, data=heartdata)
xtabs(~ heartdata$hd + heartdata$restecg, data=heartdata)
```

```{r}
logis <- glm(heartdata$hd ~ heartdata$sex, data = heartdata, family = "binomial")
summary(logis)
```

# Multiple Model Selection

```{r, message=FALSE}
library(caret)
data(iris)
dataset <- iris
head(dataset)
```

```{r}
# train:valid: 8:2
validation_index <- createDataPartition(dataset$Species, p=0.80, list=FALSE)
validation <- dataset[-validation_index,]
dataset <- dataset[validation_index,]
dim(dataset)
```

```{r}
sapply(dataset, class)
head(dataset)
levels(dataset$Species)
percentage <- prop.table(table(dataset$Species)) * 100
cbind(freq=table(dataset$Species), percentage=percentage)
```

```{r}
summary(dataset)
```

```{r}
x <- dataset[,1:4]
y <- dataset[,5]

par(mfrow=c(1,4))
for(i in 1:4) {
  boxplot(x[,i], main=names(iris)[i])
}
```

```{r}
plot(y)
```

```{r}
# scatterplot matrix
featurePlot(x=x, y=y, plot="ellipse")
```

```{r}
# box and whisker plots for each attribute
featurePlot(x=x, y=y, plot="box")
```

```{r}
# density plots for each attribute by class value
scales <- list(x=list(relation="free"), y=list(relation="free"))
featurePlot(x=x, y=y, plot="density", scales=scales)
```

```{r}
# a) linear algorithms
set.seed(7)
control <- trainControl(method = "cv", number = 10)
metric <- "Accuracy"
fit.lda <- train(Species~., data=dataset, method="lda", metric=metric, trControl=control)

# b) nonlinear algorithms
## CART
set.seed(7)
fit.cart <- train(Species~., data=dataset, method="rpart", metric=metric, trControl=control)
## kNN
set.seed(7)
fit.knn <- train(Species~., data=dataset, method="knn", metric=metric, trControl=control)

# c) advanced algorithms
## SVM
set.seed(7)
fit.svm <- train(Species~., data=dataset, method="svmRadial", metric=metric, trControl=control)
## Random Forest
set.seed(7)
fit.rf <- train(Species~., data=dataset, method="rf", metric=metric, trControl=control)
```

```{r}
# summarize accuracy of models
results <- resamples(list(lda=fit.lda, cart=fit.cart, knn=fit.knn, svm=fit.svm, rf=fit.rf))
summary(results)
```

```{r}
# compare accuracy of models
dotplot(results)
```

```{r}
# best model: LDA
print(fit.lda)
```

```{r}
# prediction on valid set
predictions <- predict(fit.lda, validation)
confusionMatrix(predictions, validation$Species)
```

```{r}
# lme() example
library(MASS)
library(nlme)
data(oats)
names(oats) <- c('block', 'variety', 'nitrogen', 'yield')
oats$mainplot <- oats$variety
oats$subplot <- oats$nitrogen
summary(oats)
```

```{r}
# summary and anova
m1.nlme <- lme(yield ~ variety*nitrogen, random = ~ 1|block/mainplot, data = oats)
summary(m1.nlme)
anova(m1.nlme)
```

