---
title: "In-class work"
author: "Zimu Lyu"
date: "10/27/2020"
output: html_document
---

```{r}
library(ISLR)
library(MASS)
library(boot)
library(randomForest)
library(rpart)
library(caret)
library(e1071)
attach(Auto)
```

```{r}
set.seed(1)
train <- sample(392, 196)
```

```{r}
lm.fit <- lm(mpg~horsepower, subset=train)
lm.fit
mean((mpg-predict(lm.fit,Auto))[-train]^2)
```

```{r}
lm.fit2 <- lm(mpg~poly(horsepower, 2), subset=train)
mean((mpg-predict(lm.fit2,Auto))[-train]^2)
```

```{r}
lm.fit3 <- lm(mpg~poly(horsepower, 3), subset=train)
mean((mpg-predict(lm.fit2,Auto))[-train]^2)
```

# resample
```{r}
set.seed(2)
train <- sample(392, 196)

lm.fit <- lm(mpg~horsepower, subset=train)
mean((mpg-predict(lm.fit,Auto))[-train]^2)

lm.fit2 <- lm(mpg~poly(horsepower, 2), subset=train)
mean((mpg-predict(lm.fit2,Auto))[-train]^2)

lm.fit3 <- lm(mpg~poly(horsepower, 3), subset=train)
mean((mpg-predict(lm.fit2,Auto))[-train]^2)
```
```{r}
data1 <- read.csv(file.choose(), header = TRUE)
head(data1)
```
```{r}
colnames(data1) <- c("BuyingPrice", "Maintenance", "NumDoors", "NumPersons", "BootSpace", "Safety", "Condition")
head(data1)
str(data1)
```
```{r}
data1$Condition <- factor(data1$Condition, levels = c("acc", "good", "unacc", "vgood"))
summary(data1)
```
```{r}
set.seed(100)
train <- sample(nrow(data1), 0.7*nrow(data1), replace = FALSE)
TrainSet <- data1[train,]
ValidSet <- data1[-train,]
summary(TrainSet)
summary(ValidSet)
```

```{r}
model1 <- randomForest(Condition ~ ., data = TrainSet, importance = TRUE)
model1
```

```{r}
model2 <- randomForest(Condition ~ ., data = TrainSet, ntree = 500, mtry = 6, importance = TRUE)
model2
```

```{r}
predTrain <- predict(model2, TrainSet, type = "class")
table(predTrain, TrainSet$Condition)
```

```{r}
predValid <- predict(model2, ValidSet, type = "class")
table(predValid, ValidSet$Condition)
```

```{r}
importance(model2)
varImpPlot(model2)
```

```{r}
a = c()
i = 5
for (i in 3:8) {
  model3 <- randomForest(Condition ~ ., data = TrainSet, ntree = 500, mtry = i, importance = TRUE)
  predValid <- predict(model3, ValidSet, type = "class")
  a[i-2] <- mean(predValid == ValidSet$Condition)
}
a
plot(3:8, a)
```

# compare with decision tree
```{r}
model_dt <- train(Condition ~ ., data = TrainSet, method = "rpart")
model_dt_1 <- predict(model_dt, TrainSet)

table(model_dt_1, TrainSet$Condition)
mean(model_dt_1 == TrainSet$Condition)
```

```{r}
model_dt_vs <- predict(model_dt, newdata = ValidSet)
table(model_dt_vs, ValidSet$Condition)
mean(model_dt_vs == ValidSet$Condition)
```

